name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIME_RANGE : all_time
          SYMBOL_VERSION: 2
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: False
          SHOW_PROFILE_VIEWS: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_TIMELINE: False
          
